---
name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install make python3 python3-sphinx python3-sphinx-rtd-theme
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Information
        run: |
          python3 -V
          sphinx-build --version
      - name: Build docs
        run: |
          make docs-clean
          make docs
      - name: Archive docs
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          path: |
            docs/dist
