---
name: lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 pycodestyle shellcheck
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Information
        run: |
          python3 -V
          bin/skonfig -V
      - name: Check PEP 8 compliance
        run: |
          make pep8
      - name: Check shell scripts
        run: |
          make shellcheck
