---
name: test-unit-optional
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: "ubuntu-18.04",  python-version: "3.3"}
          - {os: "ubuntu-18.04",  python-version: "3.4"}
          - {os: "ubuntu-18.04",  python-version: "3.5"}
          - {os: "ubuntu-18.04",  python-version: "3.6"}
          - {os: "ubuntu-18.04",  python-version: "pypy-3.6"}
          - {os: "ubuntu-18.04",  python-version: "pypy-3.7"}
          - {os: "ubuntu-latest", python-version: "pypy-3.8"}
          - {os: "ubuntu-latest", python-version: "pypy-3.9"}
          - {os: "macos-latest",  python-version: "3.5"}
          - {os: "macos-latest",  python-version: "3.6"}
          - {os: "macos-latest",  python-version: "pypy-3.8"}
          - {os: "macos-latest",  python-version: "pypy-3.9"}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Information
        run: |
          python3 -V
          bin/skonfig -V
      - name: Run unit tests
        run: |
          make unittest
