---
name: test-unit-optional
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
        python-version:
          - pypy-3.6
          - pypy-3.7
          - pypy-3.8
          - pypy-3.9
          - graalpy-22.3.1
          - graalpy-23.1.2
          - graalpy-24.1.1
        include:
          - {os: "macos",  python-version: "3.5"}
          - {os: "macos",  python-version: "3.6"}
        exclude:
          - {os: "macos",  python-version: "pypy-3.6"}
          - {os: "macos",  python-version: "pypy-3.9"}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Information
        run: |
          python3 -V
          bin/skonfig -V
      - name: Run unit tests
        run: |
          make unittest
